WARNING :< 2024-08-13 15:14:06,577 >: Неверный тип данных для объекта Runner 
-------
Traceback (most recent call last):
  File "C:\Python\pythonProject\probe\lesson58_12_4.py", line 83, in test_run
    runner_ = Runner(23545, 5)
              ^^^^^^^^^^^^^^^^
  File "C:\Python\pythonProject\probe\lesson58_12_4.py", line 20, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
WARNING :< 2024-08-13 15:14:06,578 >: Неверная скорость для Runner 
-------
Traceback (most recent call last):
  File "C:\Python\pythonProject\probe\lesson58_12_4.py", line 73, in test_walk
    runner_ = Runner('Test1',speed= -1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\pythonProject\probe\lesson58_12_4.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
